import React, { useState } from "react";
import Head from "next/head";
import styles from "../../styles/Forgotpassword.module.scss";
import Footer from "../../layouts/Footer";
import { useFormik } from "formik";
import { passUpdateValidate } from "../../lib/validate";
import axios from "axios";
import { useRouter } from "next/router";
import NoSessionNavbar from "../../layouts/NoSessionNavbar";
import { MdOutlineLockReset } from "react-icons/md";

export default function ResetPassword({ user_id }) {
  const [show, setshow] = useState(false);
  const [showIcon, setshowIcon] = useState(false);
  const [passwd, setpasswd] = useState("password");
  const [result, setResult] = useState();
  const router = useRouter();

  // hide and show password
  const checkPass = (e) => {
    if (e.target.value === "") {
      setshowIcon(false);
    } else {
      setshowIcon(true);
    }
  };

  const toggle_passwd = (e) => {
    e.preventDefault();
    if (!show) {
      setpasswd("text");
    } else {
      setpasswd("password");
    }
  };

  // form control using formik
  const formik = useFormik({
    initialValues: {
      password: "",
      cpassword: "",
    },
    validate: passUpdateValidate,
    onSubmit,
  });
  async function onSubmit(values) {
    try {
      const response = await axios.put("/api/auth/reset_password", {
        values,
        user_id,
      });
      if (response.status === 200) {
        alert("Password changed successfully.");
        router.push("/login");
      }
    } catch (error) {
      if (error.response.data.error) {
        setResult(error.response.data.error);
      }
      formik.resetForm();
      router.push("/");
    }
  }

  const removeError = () => {
    setResult("");
  };

  return (
    <>
      <NoSessionNavbar />
      <Head>
        <title>Reset Password | Famstep</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      {/* login page background */}
      <section className={styles.main_page}>
        {/* login form center */}
        <div className={styles.main_signUp}>
          {/* main form section */}
          <div className={styles.signup_form}>
            {/* form content */}
            <div className={styles.signup_form_cover}>
              <div className={styles.login_title}>
                <div
                  className={styles.VerifyIconCover}
                  style={{ paddingBottom: "1rem" }}
                >
                  <MdOutlineLockReset className={styles.VerifyReset} />
                </div>

                <p className={styles.join_famstep}>Reset Password</p>

                <div className={styles.or}>
                  <p className={styles.message}>
                    Create a new, strong password to secure your account and
                    enhance your protection.
                  </p>
                </div>
              </div>

              <form onSubmit={formik.handleSubmit} autoComplete="off">
                <div className={styles.passInput_icon}>
                  <div className={styles.input_bx}>
                    <input
                      onClick={removeError}
                      required="required"
                      type={passwd}
                      id="password"
                      className={styles.password}
                      value={formik.values.password}
                      name="password"
                      autoComplete="password"
                      onChange={(e) => {
                        formik.handleChange(e);
                        checkPass(e);
                      }}
                      onBlur={formik.handleBlur}
                      style={
                        formik.errors.password && formik.touched.password
                          ? { outline: "1px solid red" }
                          : null
                      }
                    />
                    <span className={styles.label}>Password</span>
                    {formik.errors.password && formik.touched.password && (
                      <p className={styles.errorLine}>
                        {formik.errors.password}
                      </p>
                    )}
                  </div>
                  <div
                    className={styles.passwordIcons_login}
                    onClick={toggle_passwd}
                  >
                    {showIcon ? (
                      <>
                        {show ? (
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className={styles.password_Icons}
                            viewBox="0 0 24 24"
                            onClick={() => {
                              setshow(false);
                            }}
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"
                            />
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                            />
                          </svg>
                        ) : (
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className={styles.password_Icons}
                            viewBox="0 0 24 24"
                            onClick={() => {
                              setshow(true);
                            }}
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88"
                            />
                          </svg>
                        )}
                      </>
                    ) : (
                      " "
                    )}
                  </div>
                </div>

                {/* Confirm password   */}

                <div className={styles.input_bx}>
                  <input
                    onClick={removeError}
                    type="password"
                    id="cpassword"
                    name="cpassword"
                    required="required"
                    {...formik.getFieldProps("cpassword")}
                    style={
                      formik.errors.cpassword && formik.touched.cpassword
                        ? { outline: "1px solid red" }
                        : null
                    }
                  />
                  <span className={styles.label}>Confirm Password</span>
                  {formik.errors.cpassword && formik.touched.cpassword && (
                    <p className={styles.errorLine}>
                      {formik.errors.cpassword}
                    </p>
                  )}
                </div>

                {/* idhar redirect hura sall */}
                <button type="submit" style={{ marginTop: "4rem" }}>
                  Reset Password
                </button>

                {/* extra login */}
              </form>
            </div>
          </div>
        </div>
        {/* footer section */}
        <Footer />
      </section>
    </>
  );
}

export async function getServerSideProps(context) {
  const { query } = context;
  const user_id = query.user;
  // const user_id = Jwt.verify(token, process.env.RESET_TOKEN)
  return {
    props: {
      user_id: user_id,
    },
  };
}
