import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useFormik } from "formik";
import axios from "axios";
import styles from "../styles/Forgotpassword.module.scss";
import Footer from "../layouts/Footer";
import { forgetValidate } from "../lib/validate";
import NoSessionNavbar from "../layouts/NoSessionNavbar";
import { CiLock } from "react-icons/ci";

const ForgotPassword = () => {
  const router = useRouter();
  const [result, setResult] = useState(null);

  const formik = useFormik({
    initialValues: {
      email: "",
    },
    validate: forgetValidate,
    onSubmit,
  });

  async function onSubmit(values) {
    try {
      const response = await axios.post("/api/auth/forgot_password", {
        values,
      });

      if (response.status === 200) {
        alert("Mail sent");
        setResult(null);
        formik.resetForm();
        router.push(`/emailVerify/?reset=${values.email}`);
      }
    } catch (error) {
      setResult(error.response?.data?.error);
    }
  }

  const removeError = () => {
    setResult(null);
  };

  return (
    <>
      <NoSessionNavbar />
      <Head>
        <title>Forgot Password | Famstep</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <section className={styles.main_page}>
        <div className={styles.main_signUp}>
          <div className={styles.signup_form}>
            <div className={styles.signup_form_cover}>
              <div className={styles.login_title}>
                <div className={styles.VerifyIconCover}>
                  <div className={styles.VerifyIconCircle}>
                    <CiLock className={styles.VerifyIcon} />
                  </div>
                </div>
                <p className={styles.join_famstep}>Forget Password?</p>
                <div className={styles.or}>
                  <p
                    className={styles.message}
                    style={{ padding: "1.5rem 2rem 0rem" }}
                  >
                    Please provide the email address associated with your
                    account to reset your password.
                  </p>
                </div>
              </div>
              <form onSubmit={formik.handleSubmit} autoComplete="off">
                <div className={styles.input_bx}>
                  <input
                    onClick={removeError}
                    required="required"
                    type="text"
                    id="email"
                    name="email"
                    {...formik.getFieldProps("email")}
                    style={
                      formik.errors.email && formik.touched.email
                        ? { outline: "1px solid red" }
                        : null
                    }
                  />

                  <span className={styles.label}>Email or Username</span>
                  <p
                    style={{
                      color: "red",
                      fontSize: "1.5rem",
                      marginLeft: "1rem",
                      paddingTop: ".5rem",
                    }}
                  >
                    {result}
                  </p>
                </div>

                <button type="submit">Send</button>

                <div className={styles.connectwithCover}>
                  <div className={styles.connectLine} />
                  <p className={styles.connectwith}>Or</p>
                  <div className={styles.connectLine} />
                </div>
                <div className={styles.social_icons}>
                  <Link href="/signup">
                    <span>Create a new account</span>
                  </Link>
                </div>
                <div className={styles.social_icons}>
                  <Link href="/login">
                    <span>Back to login</span>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
        <Footer />
      </section>
    </>
  );
};

export default ForgotPassword;
