import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import SignUp from "../layouts/SignUp";
import { getSession, useSession } from "next-auth/react";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Sign Up | Famstep</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
      </Head>

      <SignUp />
    </>
  );
}

export async function getServerSideProps({ req, query }) {
  const secret = process.env.JWT_SECRET;
  // const session = await getToken({
  //   req,
  //   secret,

  // })
  const session = await getSession({ req });
  const queryUser = query.user;
  // if (queryUser === "celestial-chameleon") {
    if (session) {
      return {
        redirect: {
          destination: "/network",
          permanent: false,
        },
      };
    } else if (session?.user?.isNewUser) {
      return {
        redirect: {
          destination: "/signupmoredetail",
          permanent: false,
        },
      };
    } 
  // }else {
  //   return {
  //     redirect: {
  //       destination: "/",
  //       permanent: false,
  //     },
  //   };
  // }
  return {
    props: { session },
  };
}
